### PR TITLE
Update to Kadira

### PR DESCRIPTION
**Pull request by dandv**

### CODE REVIEW

**Comment by arunoda** [comment]
Dan,

This project now moved to MeteorHacks/kadira  
Shall we refer it on the top of the Readme. What do you think?

**Comment by dandv** [comment]
Ha, I had no idea. There definitely should be a link from this README to the new repo.

Can the issues be migrated?

**Comment by arunoda** [comment]
Hmm. Not sure. It's possible. BTW: We can carry out the existing issues
here.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by dandv** [comment]
There's a [hack to move issues between repos](http://stackoverflow.com/questions/9720718/how-do-i-move-an-issue-on-github-to-another-repo).

**Comment by arunoda** [comment]
Cool. Will do it.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
 http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by arunoda** [comment]
Changed ReadMe.
And added following caption to the smart package.

```
=> Started proxy.
=> Started MongoDB.
I20140606-22:55:13.096(5.5)? ----------------------------------------------------------
I20140606-22:55:13.152(5.5)? `apm` package is deprecated!
I20140606-22:55:13.153(5.5)? Please use `kadira` package instead: http://git.io/yoagYw
I20140606-22:55:13.153(5.5)? ----------------------------------------------------------
=> Started your app.

=> App running at: http://localhost:3000/
```

**Pull request closed without merging**
